# Generated by Django 5.2.17 on 2026-09-08 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='insight',
            options={'ordering': ['-published_at']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['order', 'name']},
        ),
    ]
